
# Eatery.create(bar:true, name: "OTB", non_veg: true, card_type: "credit", buffet: false, outdoor_seating: true, home_delievery: false )
# Eatery.create(bar:true, name: "Raasta", non_veg: true, card_type: "debit", buffet: false, outdoor_seating: true, home_delievery: true )
# Eatery.create(bar:true, name: "Fork You", non_veg: false, card_type: "credit", buffet: true, outdoor_seating: true, home_delievery: true )
# Eatery.create(bar:true, name: "Blue Frog", non_veg: true, card_type: "credit", buffet: true, outdoor_seating: false, home_delievery: false )
# Eatery.create(bar:true, name: "Thirty Nine", non_veg: true, card_type: "credit", buffet: false, outdoor_seating: true, home_delievery: true )
# Eatery.create(bar:true, name: "Pink Room", non_veg: true, card_type: "credit", buffet: false, outdoor_seating: false, home_delievery: false )
# Eatery.create(bar:true, name: "CDB", non_veg: true, card_type: "debit", buffet: false, outdoor_seating: true, home_delievery: false )
# Eatery.create(bar:true, name: "Underdogs", non_veg: true, card_type: "credit", buffet: false, outdoor_seating: true, home_delievery: false )
# Eatery.create(bar:true, name: "Strikers", non_veg: true, card_type: "credit", buffet: true, outdoor_seating: false, home_delievery: true )
# Eatery.create(bar:true, name: "Howzzatt", non_veg: false, card_type: "debit", buffet: false, outdoor_seating: true, home_delievery: false )
# Eatery.create(bar:true, name: "Claridges", non_veg: true, card_type: "credit", buffet: true, outdoor_seating: true, home_delievery: false )
# Eatery.create(bar:true, name: "Hard Rock Cafe", non_veg: true, card_type: "debit", buffet: false, outdoor_seating: false, home_delievery: false )
# Eatery.create(bar:true, name: "Cafe Morrisson", non_veg: false, card_type: "credit", buffet: true, outdoor_seating: true, home_delievery: true )
# Eatery.create(bar:true, name: "Route O4", non_veg: true, card_type: "debit", buffet: false, outdoor_seating: true, home_delievery: false )
# Eatery.create(bar:true, name: "Mia Bella", non_veg: false, card_type: "credit", buffet: true, outdoor_seating: true, home_delievery: false )


# eatery = Eatery.find_by_name('Blue Frog')
# eatery.locations.create(name: 'Mumbai', contact_number: "23456")
# eatery.locations.create(name: 'Delhi', contact_number: "23356")
# eatery = Eatery.find(4)
# eatery.cuisines.create(name: "Deserts")
# eatery.cuisines.create(name: "Chinese")
# eatery.cuisines.create(name: "Continental")

# eatery = Eatery.find_by_name('OTB')
# eatery.locations.create(name: 'Delhi', contact_number: "22456")
# eatery.locations.create(name: 'Noida', contact_number: "234336")
# eatery.cuisines.create(name: "Fast Food")
# eatery.cuisines.create(name: "Sea Food")
# eatery.cuisines.create(name: "Street Food")

# eatery = Eatery.find_by_name('Strikers')
# eatery.locations.create(name: 'Gurgaon', contact_number: "223456")
# eatery.cuisines.create(name: "Mughlai")
# eatery.cuisines.create(name: "Italian")
# eatery.cuisines.create(name: "American")

# eatery = Eatery.find_by_name('Claridges')
# eatery.locations.create(name: 'Faridabad', contact_number: "2332356")
# eatery.cuisines.create(name: "Mughlai")
# eatery.cuisines.create(name: "Chinese")
# eatery.cuisines.create(name: "Continental")


# eatery = Eatery.find_by_name('Hard Rock Cafe')
# eatery.locations.create(name: 'Mumbai', contact_number: "2345322")
# eatery.locations.create(name: 'Delhi', contact_number: "2345322")
# eatery.locations.create(name: 'Hyderabad', contact_number: "2345322")
# eatery.cuisines.create(name: "Deserts")
# eatery.cuisines.create(name: "American")
# eatery.cuisines.create(name: "Italian")

# eatery = Eatery.find_by_name('Mia Bella')
# eatery.locations.create(name: 'HKV', contact_number: "234536")
# eatery.cuisines.create(name: "Sea Food")
# eatery.cuisines.create(name: "Mughlai")
# eatery.cuisines.create(name: "Continental")

# eatery = Eatery.find_by_name('Cafe Morrisson')
# eatery.locations.create(name: 'Delhi', contact_number: "232456")
# eatery.cuisines.create(name: "Street Food")
# eatery.cuisines.create(name: "Sea Food")
# eatery.cuisines.create(name: "American")


# eatery = Eatery.find_by_name('Route O4')
# eatery.locations.create(name: 'Connaught Place', contact_number: "2343356")
# eatery.locations.create(name: 'Gurgaon', contact_number: "2343356")
# eatery.cuisines.create(name: "American")
# eatery.cuisines.create(name: "Chinese")
# eatery.cuisines.create(name: "Sea Food")

# eatery = Eatery.find_by_name('Howzzatt')
# eatery.locations.create(name: 'Gurgaon', contact_number: "23452236")
# eatery.cuisines.create(name: "Italian")
# eatery.cuisines.create(name: "Chinese")
# eatery.cuisines.create(name: "Street Food")

# eatery = Eatery.find_by_name('Underdogs')
# eatery.locations.create(name: 'Delhi', contact_number: "2345236")
# eatery.locations.create(name: 'Gurgaon', contact_number: "2345236")
# eatery.cuisines.create(name: "American")
# eatery.cuisines.create(name: "Street Food")
# eatery.cuisines.create(name: "Continental")

# eatery = Eatery.find_by_name('CDB')
# eatery.locations.create(name: 'Faridabad', contact_number: "23453326")
# eatery.locations.create(name: 'Delhi', contact_number: "23453326")
# eatery.cuisines.create(name: "Mughlai")
# eatery.cuisines.create(name: "Chinese")
# eatery.cuisines.create(name: "Street Food")

# eatery = Eatery.find_by_name('Pink Room')
# eatery.locations.create(name: 'Delhi', contact_number: "2345556")
# eatery.cuisines.create(name: "Deserts")
# eatery.cuisines.create(name: "Bakery")
# eatery.cuisines.create(name: "Continental")

# eatery = Eatery.find_by_name('Thirty Nine')
# eatery.locations.create(name: 'Delhi', contact_number: "2345556")
# eatery.cuisines.create(name: "Deserts")
# eatery.cuisines.create(name: "Chinese")
# eatery.cuisines.create(name: "Bakery")


# eatery = Eatery.find_by_name('Raasta')
# eatery.locations.create(name: 'Delhi', contact_number: "2345556")
# eatery.cuisines.create(name: "Deserts")
# eatery.cuisines.create(name: "Italian")
# eatery.cuisines.create(name: "Bakery")

# eatery = Eatery.find_by_name('Claridges')
# eatery.locations.create(name: 'Mumbai', contact_number: "2345336")
# eatery.cuisines.create(name: "Italian")
# eatery.cuisines.create(name: "American")
# eatery.cuisines.create(name: "Continental")

# eatery = Eatery.find_by_name('Fork You')
# eatery.locations.create(name: 'Hyderabad', contact_number: "2345336")
# eatery.cuisines.create(name: "Bakery")
# eatery.cuisines.create(name: "American")
# eatery.cuisines.create(name: "Chaat")

# puts "seeding done"